# Generated by minlang-core scripts/gen_packaging.py — do not edit.
class Ml1 < Formula
  desc "MinLang compiler (validate + compile to Godot/C# and web/TypeScript)"
  homepage "https://github.com/codeshift-ai-solutions/minlang-releases"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/codeshift-ai-solutions/minlang-releases/releases/download/v0.6.2/ml1-v0.6.2-aarch64-apple-darwin.tar.gz"
      sha256 "01705adf4fc14ec8e203b52a1c85ab5377f3f953bf8a81bde92f1e27e615017e"
    else
      url "https://github.com/codeshift-ai-solutions/minlang-releases/releases/download/v0.6.2/ml1-v0.6.2-x86_64-apple-darwin.tar.gz"
      sha256 "92cecc5606656dbc7a3a61fb1d830b651bfca80ce95de99bd7c9d69e0c395dc3"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/codeshift-ai-solutions/minlang-releases/releases/download/v0.6.2/ml1-v0.6.2-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "a54f01ecd45d999b5cb8ecade256de9c30f9ff8bb96c31157ba71501b9a538be"
    else
      url "https://github.com/codeshift-ai-solutions/minlang-releases/releases/download/v0.6.2/ml1-v0.6.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "037c49bb63c6a261d16fd8be75b27e496f087b171a14d1db9f830614f08a5d86"
    end
  end

  def install
    bin.install "ml1"
  end

  test do
    assert_match "MinLang", shell_output("#{bin}/ml1")
  end
end
