# Generated by minlang-core scripts/gen_packaging.py — do not edit.
class Ml1 < Formula
  desc "MinLang compiler (validate + compile to Godot/C# and web/TypeScript)"
  homepage "https://github.com/codeshift-ai-solutions/minlang-releases"
  license "MIT"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/codeshift-ai-solutions/minlang-releases/releases/download/v0.4.0/ml1-v0.4.0-aarch64-apple-darwin.tar.gz"
      sha256 "9a6a62c1fba713c6fa90a181f7b1b062015e62e03253462e837167451ed940fa"
    else
      url "https://github.com/codeshift-ai-solutions/minlang-releases/releases/download/v0.4.0/ml1-v0.4.0-x86_64-apple-darwin.tar.gz"
      sha256 "2fcd8700598273748ca53d8ce7963f75eb2b5b4486182a5fdc98cd260dd29a85"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/codeshift-ai-solutions/minlang-releases/releases/download/v0.4.0/ml1-v0.4.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "47067a9401cf81ece4da21f8347c1fd3c8d16a6a42a33d4ef0b5200a67e64ea3"
    else
      url "https://github.com/codeshift-ai-solutions/minlang-releases/releases/download/v0.4.0/ml1-v0.4.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "81e06ee9c77571917f4ebadf4d88ee2bfaf73864825464870af005a3aa4c7410"
    end
  end

  def install
    bin.install "ml1"
  end

  test do
    assert_match "MinLang", shell_output("#{bin}/ml1")
  end
end
