# Generated by minlang-core scripts/gen_packaging.py — do not edit.
class Ml1 < Formula
  desc "MinLang compiler (validate + compile to Godot/C# and web/TypeScript)"
  homepage "https://github.com/codeshift-ai-solutions/minlang-releases"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/codeshift-ai-solutions/minlang-releases/releases/download/v0.6.3/ml1-v0.6.3-aarch64-apple-darwin.tar.gz"
      sha256 "d7c4eb41063d3ac56f7e1f0f305b3020919aa5b451ac6cf9374725e4e686ada9"
    else
      url "https://github.com/codeshift-ai-solutions/minlang-releases/releases/download/v0.6.3/ml1-v0.6.3-x86_64-apple-darwin.tar.gz"
      sha256 "598df79e9809b40c5be34e744d233d63fcd4de3529a1c05da7d35a9f30be7fa8"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/codeshift-ai-solutions/minlang-releases/releases/download/v0.6.3/ml1-v0.6.3-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "143989d77d6a1e510fb77d6ff420483e83f3b11db466af4505a33c36b23cbb19"
    else
      url "https://github.com/codeshift-ai-solutions/minlang-releases/releases/download/v0.6.3/ml1-v0.6.3-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "3f1f81d5402cd15323de7ef9701b64ca24e91b3ec1cb6984695ac1f59a8ad26d"
    end
  end

  def install
    bin.install "ml1"
  end

  test do
    assert_match "MinLang", shell_output("#{bin}/ml1")
  end
end
